# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotID', models.FloatField()),
                ('date', models.DateTimeField()),
                ('exch', models.CharField(max_length=100)),
                ('open', models.FloatField(blank=True)),
                ('close', models.FloatField(blank=True)),
                ('high', models.FloatField(blank=True)),
                ('low', models.FloatField(blank=True)),
                ('volume', models.BigIntegerField(blank=True)),
                ('openInterest', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
