# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0002_auto_20180126_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='futdaily',
            name='instID',
            field=models.FloatField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='futdaily',
            name='date',
            field=models.DateTimeField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='futdaily',
            name='exch',
            field=models.CharField(max_length=100, primary_key=True),
        ),
        migrations.RemoveField(
            model_name='futdaily',
            name='id',
        ),
        migrations.RemoveField(
            model_name='futdaily',
            name='spotID',
        ),
        migrations.AlterUniqueTogether(
            name='futdaily',
            unique_together=set([('instID', 'date', 'exch')]),
        ),
    ]
