# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0003_auto_20180126_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futdaily',
            name='instID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
