# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0004_auto_20180126_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futdaily',
            name='date',
            field=models.CharField(max_length=1000, primary_key=True),
        ),
    ]
