# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0006_auto_20180126_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futdaily',
            name='date',
            field=models.DateTimeField(primary_key=True),
        ),
    ]
