# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0007_auto_20180126_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('article', models.TextField()),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
