# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0008_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
