# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotting', '0009_auto_20180222_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='pair',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='author',
            field=models.CharField(default='Julian', max_length=100),
        ),
    ]
